load("@npm_bazel_typescript//:defs.bzl", "ts_library")

ts_library(
    name = "tutorial",
    srcs = [
        "tutorial.ts",
        "tutorial_data.ts",
    ],
    visibility = [
        "//visibility:public",
    ],
)
