java_library(
    name = "r5js",
    srcs = glob(["*.java"]),
    deps = [
        "@closure_compiler_externs//jar",
        "@my_closure_compiler//jar",
        "@my_guava//jar",
        "@truth//jar",
        "@junit//jar",
    ],
)
