(define (atom? x) (not (or (pair? x) (null? x))))

(define (run-tests tests)
  (define (run-tests-tail tests num-tests num-failures)
    (if (null? tests)
	(begin (display num-tests)
	       (display " tests, ")
	       (display num-failures)
	       (display " failures")
	       (display #\newline))
	(let* ((cur-test (car tests))
	       (input (car cur-test))
	       (expected-output (cdr cur-test))
	       (actual-output (eval input (interaction-environment))))
	  (if (equal? expected-output actual-output)
	      (run-tests-tail (cdr tests) (+ 1 num-tests) num-failures)
	      (begin (display "error evaluating ")
		     (display input)
		     (display ": expected ")
		     (display expected-output)
		     (display ", got ")
		     (display actual-output)
		     (display #\newline)
		     (run-tests-tail
		      (cdr tests)
		      (+ 1 num-tests)
		      (+ 1 num-failures)))))))
  (run-tests-tail tests 0 0))

(define ch1-tests
  '(
    ((atom? 'atom) . #t)
    ((atom? 'turkey) . #t)
    ((atom? 1492) . #t)
    ((atom? 'u) . #t)
    ((atom? '*abc$) . #t)
    ((list? '(atom)) . #t)
    ((list? '(atom turkey or)) . #t)
    ((list? '((atom turkey) or)) . #t)
    ((length '(how are you doing so far)) . 6)
    ((list? '(((how) are) ((you) (doing so)) far)) . #t)
    ((length '(((how) are) ((you) (doing so)) far)) . 3)
    ((list? '()) . #t)
    ((atom? '()) . #f)
    ((list? '(() () () ())) . #t)
    ((car '(a b c)) . a)
    ((car '((a b c) x y z)) . (a b c))
					;((car 'hotdog) . 'error)
					;((car '()) . 'error)
    ((car '(((hotdogs)) (and) (pickle) relish)) . ((hotdogs)))
    ((car (car '(((hotdogs)) (and)))) . (hotdogs))
    ((cdr '(a b c)) . (b c))
    ((cdr '((a b c) x y z)) . (x y z))
					;  ((cdr 'hamburger) . 'error)
    ((cdr '((x) t r)) . (t r))
					;  ((cdr 'hotdogs) . 'error)
					;  ((cdr '()) . 'error)
    ((car (cdr '((b) (x y) ((c))))) . (x y))
    ((cdr (cdr '((b) (x y) ((c))))) . (((c))))
					;  ((cdr (car '(a (b (c)) d))) . 'error)
    ((cons 'peanut '(butter and jelly)) . (peanut butter and jelly))
    ((cons '(banana and) '(peanut butter and jelly)) . ((banana and) peanut butter and jelly))
    ((cons '((help) this) '(is very ((hard) to learn))) . (((help) this) is very ((hard) to learn)))
    ((cons '(a b (c)) '()) . ((a b (c))))
    ((cons 'a '()) . (a))
    ((cons '((a b c)) 'b) . (((a b c)) . b))
    ((cons 'a 'b) . (a . b))
    ((cons 'a (car '((b) c d))) . (a b))
    ((cons 'a (cdr '((b) c d))) . (a c d))
    ((null? '()) . #t)
    ((null? (quote ())) . #t)
    ((null? '(a b c)) . #f)
    ((null? 'spaghetti) . #f)
    ((atom? 'Harry) . #t)
    ((atom? '(Harry had a heap of apples)) . #f)
    ((atom? (car '(Harry had a heap of apples))) . #t)
    ((atom? (cdr '(Harry had a heap of apples))) . #f)
    ((atom? (cdr '(Harry))) . #f)
    ((atom? (car (cdr '(swing low sweet cherry oat)))) . #t)
    ((atom? (car (cdr '(swing (low sweet) cherry oat)))) . #f)
    ((eq? 'Harry 'Harry) . #t)
    ((eq? 'margarine 'butter) . #f)
    ((eq? '() '(strawberry)) . #f)
    ((eq? 6 7) . #f)
    ((eq? (car '(Mary had a little lamb chop)) 'Mary) . #t)
    ((eq? (cdr '(soured milk)) 'milk) . #f)
    ((let ((l '(beans beans we need jelly beans)))
       (eq? (car l) (car (cdr l)))) . #t)
    ))


					; todo bl -- integrate within tests
(define (all? pred? xs)
  (cond
   ((null? xs) #t)
   ((pred? (car xs)) (all? pred? (cdr xs)))
   (else #f)))
(define (lat? l)
  (all? atom? l))
(define (member? x ys)
  (cond
   ((null? ys) #f)
   ((eq? x (car ys)) #t)
   (else (member? x (cdr ys)))))

(define ch2-tests
  '(
    ((lat? '(Jack Sprat could eat no chicken fat)) . #t)
    ((lat? '((Jack) Sprat could eat no chicken fat)) . #f)
    ((lat? '(Jack (Sprat could) eat no chicken fat)) . #f)
    ((lat? '()) . #t)
    ((lat? '(bacon and eggs)) . #t)
    ((lat? '(bacon (and eggs))) . #f)
    ((or (null? '()) (atom? '(d e f g))) . #t)
    ((or (null? '(a b c)) (null? '())) . #t)
    ((or (null? '(a b c)) (null? '(atom))) . #f)
    ((member? 'tea '(coffee tea or milk)) . #t)
    ((member? 'poached '(fried eggs and scrambled eggs)) . #f)
    ((member? 'meat '(mashed potatoes and meat gravy)) . #t)
    ((member? 'liver '(bagels and lox)) . #f)
    ))

(define (rember x ys)
  (cond
   ((null? ys) ys)
   ((eq? x (car ys)) (cdr ys))
   (else (cons
	  (car ys)
	  (rember x (cdr ys))))))

(define (filter pred? xs)
  (if (null? xs)
      '()
      (let ((cur (car xs))
	    (rest (cdr xs)))
	(if (pred? cur)
	    (cons cur (filter pred? rest))
	    (filter pred? rest)))))

(define (multirember x ys)
  (filter (lambda (y) (not (eq? x y))) ys))

(define (firsts lists)
  (map car lists))

(define (insertR new old list)
  (if (null? list)
      '()
      (let ((cur (car list)))
	(if (eq? old cur)
	    (cons (car list)
		  (cons new
			(cdr list)))
	    (cons (car list)
		  (insertR new old (cdr list)))))))

(define (subst new old list)
  (if (null? list)
      '()
      (let ((cur (car list)))
	(if (eq? cur old)
	    (cons new (cdr list))
	    (cons cur (subst new old (cdr list)))))))

(define (subst2 new old1 old2 list)
  (if (null? list)
      '()
      (let ((cur (car list)))
	(if (or (eq? cur old1)
		(eq? cur old2))
	    (cons new (cdr list))
	    (cons cur (subst2 old1 old2 (cdr list)))))))

;; (define (multiinsertR new old list)
;;   (if (null? list)
;;       '()
;;       (let ((cur (car list))
;; 	    (rest (cdr list)))
;; 	(if (eq? cur old)
;; 	    (cons old
;; 		  (cons new
;; 			(multiinsertR new old rest)))
;; 	    (multiinsertR new old rest)))))

(define ch3-tests
  '(
    ((rember 'mint '(lamb chops and mint jelly)) . (lamb chops and jelly))
    ((rember 'mint '(lamb chops and mint flavored jelly)) . (lamb chops and flavored jelly))
    ((rember 'toast '(bacon lettuce and tomato)) . (bacon lettuce and tomato))
    ((rember 'cup '(coffee cup tea cup and hick cup)) . (coffee tea cup and hick cup))
    ((firsts '((apple peach pumpkin)
	       (plum pear cherry)
	       (grape raisin pea)
	       (bean carrot eggplant))) . (apple plum grape bean))
    ((firsts '((a b) (c d) (e f))) . (a c e))
    ((firsts '()) . ())
    ((firsts '((five plums)
	       (four)
	       (eleven green oranges))) . (five four eleven))
    ((firsts '(((five plums) four)
	       (eleven green oranges)
	       ((no) more))) . ((five plums) eleven (no)))
    ((insertR 'topping 'fudge '(ice cream with fudge for dessert))
     . (ice cream with fudge topping for dessert))
    ((insertR 'jalapeno 'and '(tacos tamales and salsa))
     . (tacos tamales and jalapeno salsa))
    ((insertR 'e 'd '(a b c d f g d h))
     . (a b c d e f g d h))
    ((subst 'topping 'fudge '(ice cream with fudge for dessert))
     . (ice cream with topping for dessert))
    ((subst2
      'vanilla
      'chocolate
      'banana
      '(banana ice cream with chocolate topping))
     . (vanilla ice cream with chocolate topping))
    ((multirember 'cup '(coffee cup tea cup and hick cup))
     . (coffee tea and hick))
    ))