; This file contains the unit testing framework (not the tests themselves).

(define (run-tests name tests)
  (define (run-tests-tail name tests num-tests num-failures)
    (if (null? tests)
	(begin (display name)
	       (display num-tests)
	       (display "tests,")
	       (display num-failures)
	       (display "failures")
	       (display #\newline))
	(let* ((cur-test (car tests))
	       (input (car cur-test))
	       (expected-output (cdr cur-test))
	       (actual-output (eval input (scheme-report-environment 5))))
	  (if (equal? expected-output actual-output)
	      (run-tests-tail name (cdr tests) (+ 1 num-tests) num-failures)
	      (begin (display "error evaluating")
		     (display input)
		     (display ": expected")
		     (display expected-output)
		     (display ", got")
		     (display actual-output)
		     (display #\newline)
		     (run-tests-tail
		      name
		      (cdr tests)
		      (+ 1 num-tests)
		      (+ 1 num-failures)))))))
  (run-tests-tail name tests 0 0))

(define-syntax define-tests
  (syntax-rules ()
    ((define-tests name tests)
     (run-tests (quote name) tests))))