#!/bin/sh
# (ln -s this file to .git/hooks/pre-commit.)
echo 'linting...'
eval 'make lint'
ret_code=$?
if [ $ret_code != 0 ]; then
    echo 'lint errors, aborting commit'
    exit $ret_code
fi
echo 'type-checking...'
eval 'make typecheck'
ret_code=$?
if [ $ret_code != 0 ]; then
    echo 'type errors, aborting commit'
    exit $ret_code
fi
echo 'testing...'
eval 'make test'
ret_code=$?
if [ $ret_code != 0 ]; then
    echo 'failure(s) in tests, aborting commit'
    exit $ret_code
fi
