load("@build_bazel_rules_typescript//:defs.bzl", "ts_library")

package(
    default_visibility = ["//js:__subpackages__"],
)

exports_files([
    "ellipsis_transformer.ts",
    "list_like_transformer.ts",
    "macro.ts",
    "macro_id_transformer.ts",
    "rename_helper.ts",
    "subtransformer.ts",
    "template_bindings.ts",
    "transformer.ts",
])